import { ClinicaResponse } from '../types/clinic';

/**
 * Catálogo estático e imutável de clínicas parceiras e atendimento 24h/emergência.
 * Mantido como recurso constante do ecossistema Clyvo Care.
 */
export const CLINICAS_CATALOGO: readonly ClinicaResponse[] = [
  {
    id: 1,
    nome: 'Hospital Veterinário Clyvo 24h',
    telefone: '(11) 3456-7890',
    rua: 'Av. Paulista',
    numero: '1106',
    bairro: 'Bela Vista',
    cidade: 'São Paulo',
    estado: 'SP',
    atendimento24h: true,
    prontoSocorro: true,
    patrocinada: true,
    avaliacao: 4.9,
    distanciaKm: 1.2,
    especialidades: ['Emergência 24h', 'Cirurgia', 'UTI', 'Raio-X', 'Ultrassom'],
  },
  {
    id: 2,
    nome: 'Pronto Socorro Pet São Paulo',
    telefone: '(11) 2345-6789',
    rua: 'Rua Domingos de Morais',
    numero: '2564',
    bairro: 'Vila Mariana',
    cidade: 'São Paulo',
    estado: 'SP',
    atendimento24h: true,
    prontoSocorro: true,
    patrocinada: true,
    avaliacao: 4.8,
    distanciaKm: 2.5,
    especialidades: ['Pronto-Socorro', 'Ortopedia', 'Internação'],
  },
  {
    id: 3,
    nome: 'Clínica Veterinária Vida Animal',
    telefone: '(11) 98765-4321',
    rua: 'Rua Augusta',
    numero: '1500',
    bairro: 'Consolação',
    cidade: 'São Paulo',
    estado: 'SP',
    atendimento24h: false,
    prontoSocorro: false,
    patrocinada: false,
    avaliacao: 4.6,
    distanciaKm: 3.1,
    especialidades: ['Vacinação', 'Consultas', 'Dermatologia'],
  },
  {
    id: 4,
    nome: 'Centro Médico Veterinário Jardins',
    telefone: '(11) 3088-1234',
    rua: 'Alameda Lorena',
    numero: '850',
    bairro: 'Jardins',
    cidade: 'São Paulo',
    estado: 'SP',
    atendimento24h: true,
    prontoSocorro: true,
    patrocinada: true,
    avaliacao: 4.9,
    distanciaKm: 3.8,
    especialidades: ['Emergência', 'Cardiologia', 'Exames Laboratoriais'],
  },
  {
    id: 5,
    nome: 'PetCare Higienópolis',
    telefone: '(11) 3662-9988',
    rua: 'Rua Maranhão',
    numero: '420',
    bairro: 'Higienópolis',
    cidade: 'São Paulo',
    estado: 'SP',
    atendimento24h: true,
    prontoSocorro: false,
    patrocinada: false,
    avaliacao: 4.7,
    distanciaKm: 4.5,
    especialidades: ['Consultas 24h', 'Oftalmologia', 'Acupuntura'],
  },
];
