export const STORAGE_KEYS = {
    AUTH_TOKEN: "@PetGuardian_AuthToken",
    AUTH_USER: "@PetGuardian_AuthUser",
    ACTIVE_PET_ID: "@PetGuardian_ActivePetId",
    USER_DATA: "@PetGuardian_UserData",
    LOGADO: "@PetGuardian_Logado",
    CUIDADORES: "@Familia_Cuidadores",
    RECADOS: "@Familia_Recados",
    FAMILIA_ATIVA: "@PetGuardian_FamiliaAtiva",
    NOME_FAMILIA: "@PetGuardian_NomeFamilia",
    LISTA_PETS: "@PetGuardian_ListaPets",
    CODIGO_FAMILIA: "@PetGuardian_CodigoFamilia",
    PONTOS_XP: "@PetGuardian_PontosXP",
    OFENSIVA_DIAS: "@PetGuardian_OfensivaDias",
    ULTIMO_DIA_ACESSO: "@PetGuardian_UltimoDiaAcesso",
    DATA_ULTIMA_OFENSIVA: "@PetGuardian_DataUltimaOfensiva",
    TAREFA_VERMIFUGO_ATIVA: "@PetGuardian_TarefaVermifugoAtiva",
    FAMILIA_TAREFAS: "@PetGuardian_FamiliaTarefas",
    PROGRESSO_PREFIX: "@PetGuardian_Progresso_"
};